handle wrong plugin metadata on server case - issue #110
Encapsia/encapsia-cli pull request #114
Opened 2023-02-02 09:37 UTC by mpopetcmed

bug #110 

if there are some invalid entries in the pluginsmanager tables (https://cmedtechnology.atlassian.net/browse/ENC-4163), some encapsia plugins subcommands will fail.

This fix ensures the missing metadata case is handled and notifies the user about the exception (messages + return codes)

2023-02-03 09:06 UTC, petrem requested changes

2023-02-03 09:06 UTC, petrem commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
But you have to deduce from the verbose error message which plugins are affected.
(Similarly for when installing multiple plugins and one has the manifest problem, you have to read the json to determine which one is defiled).
I wonder, could we mark them in red in the output? Help uses notice, plus otherwise they'd need to understand the plugin manifest structure (pretty obvious, but still).

I marked the lines i mean in the output below:
```
1 > poetry run encapsia --host localhost plugins install --ignore-warnings datapointslib tutor
Missing important information for plugin {'plugin_id': '974fc7546705418d89c56ee7f9e852a9', 'name': 'datapointslib', 'version': '1.1.0', 'description': "Library to obtain 'tall thin' table of datapoints.", 'blob_id': '93e9696982924b149ac2303d965c8a9b', 'pluginlog_id': '3bf47740beaa41a080bf2b35dd685421', 'when': '2023-02-03T08:26:50.315189+00:00', 'manifest': None}
name*          existing version**    new version**    action
-------------  --------------------  ---------------  --------
datapointslib  1.1.0                 1.1.0            skip      <----- have this red
tutor                                1.1.9            install

✖1 > poetry run encapsia --host localhost plugins status
Missing important information for plugin {'plugin_id': '974fc7546705418d89c56ee7f9e852a9', 'name': 'datapointslib', 'version': '1.1.0', 'description': "Library to obtain 'tall thin' table of datapoints.", 'blob_id': '93e9696982924b149ac2303d965c8a9b', 'pluginlog_id': '3bf47740beaa41a080bf2b35dd685421', 'when': '2023-02-03T08:26:50.315189+00:00', 'manifest': None}
name*          version**    available**    installed
-------------  -----------  -------------  ------------------------
datapointslib  1.1.0        <same>         Fri 03 Feb 2023 08:26:50      <--- have this red
manager        1.2.9        2.0.0-52       Wed 01 Feb 2023 10:45:36

(*) Plugin variant shown in square brackets when defined.
(**) Equivalent semver versions are shown in brackets when non-semver version is used.
There were some errors in the plugin metadata retrieved from server
Aborted!


```

2023-02-03 13:51 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +    def make_from_encapsia(host: str, errors_list=None) -> PluginInfos:
In almost all cases where it is used, the result of calling `PluginInfos.make_from_encapsia(host)` is not stored in a local variable, but instead is directly used as a parameter to another call:

`to_install_candidates.extend(
            PluginSpec(pi.name, pi.variant)
            for pi in PluginInfos.make_from_encapsia(host)
        )`

`versions = PluginSpecs.make_from_plugininfos(
        PluginInfos.make_from_encapsia(obj["host"], errors_list)
    ).as_version_dict()`

In cases the error information were a attribute of the `PluginInfos` instance, it would be required to store it in a local variable, in order to subsequently access it.
Similarly, if the result was part of a tuple, it would be tricky to maintain the existing code.
That is the reason I chose passing 'by reference' the container.

2023-02-03 13:53 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +            if any(i.get(key) is None for key in ("name", "version")):
agreed, will add the comments

2023-02-03 13:58 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +                if errors_list is not None and i not in errors_list:
yes, but for small lists (less than say 5 elements), nothing beats linear search (including for cache hits reason)

2023-02-03 13:59 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +                    "installed": _format_datetime(i.get("when"))
black & friends have been summoned

2023-02-03 13:59 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +    if len(errors_list):
ok

2023-02-03 14:01 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +            if any(i.get(key) is None for key in ("name", "version")):
I imagined the devs would be called to figure out the error and the code is pretty explanatory

2023-02-03 14:02 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +            tags = i.get("manifest", {}).get("tags")
beat around the bush, I did

2023-02-03 14:04 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +    "--ignore-warnings",
yes, but I considered --ignore-warnings more appropriate, since it won't do the dangerous parts, it will try to perform only the safe parts of the task

2023-02-03 14:07 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
![image](https://user-images.githubusercontent.com/11572028/216623429-48da0bf4-9509-41a4-9eaf-69fa484965d7.png)


do you mean to paint in red only the offending part of the json?

2023-02-03 14:46 UTC, petrem commented on encapsia_cli/plugininfo.py
> +            if any(i.get(key) is None for key in ("name", "version")):
Automation will replace you, anyway. Why wouldn't you give yourself an easier time, meanwhile? ;-)

2023-02-03 15:07 UTC, petrem commented on encapsia_cli/plugins.py
> +    "--ignore-warnings",
Yes but you are still ignoring errors, not warnings. To me, `--ignore-warnings` is even less saying what the option really does. We could use `--unwavering` :).

2023-02-03 15:09 UTC, petrem commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
No, I mean to paint red the lines I marked with `<---- have this red` in my examples.
Painting the json, while neat, would probably be more work than worth it. My suggestion stands only if it is easy to implement.

2023-02-03 15:14 UTC, petrem commented on encapsia_cli/plugininfo.py
> +    def make_from_encapsia(host: str, errors_list=None) -> PluginInfos:
Ok, I guess. I still find it an abomination unto Nuggan, but be it on your soul. We can revisit when we refactor this area, we need to do anyway.

2023-02-03 15:23 UTC, petrem commented on encapsia_cli/plugininfo.py
> +                if errors_list is not None and i not in errors_list:
> yes, but for small lists (less than say 5 elements), nothing beats linear search (including for cache hits reason)

Apparently not in python (tested in 3.11):
```
In [1]: l1 = ["these", "are", "a", "few", "of", "my", "favourite", "things"]

In [2]: s1 = set(l1)

In [3]: %timeit ("foo" in l1, "my" in l1)
186 ns ± 0.467 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [4]: %timeit ("foo" in l1, "my" in s1)
139 ns ± 1.23 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [5]: %timeit ("foo" in l1, "my" in l1)
186 ns ± 0.836 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```
(and just for the fun of it, it makes no difference for us here)

2023-02-03 17:53 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +                if errors_list is not None and i not in errors_list:
TypeError: unhashable type: 'dict'

you know this is a utter waste of time, what are the chances of having any errors in the plugins view dump caused by missing 'manifest' AND TooManyVariantTagsError thrown?

yet we are trying to optimize this case..

2023-02-03 17:58 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +    "--ignore-warnings",
'--nobody-will-ever-use-this-option'?

2023-02-03 18:01 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
oh, I missed the `have this red ` annotation

yes,it could be a nice enhancement, will look into it

red/green for color blind people? :)

2023-02-03 20:14 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
are you ok with this output?

![image](https://user-images.githubusercontent.com/11572028/216700811-60600686-b4c8-491c-8a8c-ea987effd435.png)

`encapsia plugins freeze` output has been changed a bit (in case there's a variant besides version it is better than before, IMO)

![image](https://user-images.githubusercontent.com/11572028/216701163-d17e2529-bb03-4237-9156-3011207e486c.png)

For `encapsia plugins status` it's using a reversed print instead of red that might be hard to differentiate from 'yellow' orange (I admit I was tempted to use `blink` - but that would have been to 80'ish

2023-02-03 20:18 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +            if any(i.get(key) is None for key in ("name", "version")):
ok, I'll take a look at code-pilot pricing tiers

2023-02-04 05:56 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +                    "installed": _format_datetime(i.get("when"))
I found another format so black would not screw it completely

2023-02-04 06:15 UTC, mpopetcmed commented on encapsia_cli/plugininfo.py
> +            if any(i.get(key) is None for key in ("name", "version")):
Code-pilot is really useful, it helped me add extra information about what's wrong with the plugins!

2023-02-06 08:03 UTC, petrem commented on encapsia_cli/plugininfo.py
> +                if errors_list is not None and i not in errors_list:
If you'd cared to read my message, I specifically said we don't need to optimize this case as its performance is irrelevant. I did not suggest what I suggested for performance reasons. I was curious to check if indeed sets are slower than short lists for lookups, in python -- and apparently they aren't. I'm sorry I shared this trivial fact and wasted 3 minutes of your precious time :P

2023-02-06 08:05 UTC, petrem commented on encapsia_cli/plugins.py
> +    "--ignore-warnings",
sounds good

2023-02-06 08:08 UTC, petrem commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
thank you for not using blink :) 
output looks good, but why is the plugin (datapointslib in this case) show up twice?

2023-02-06 08:27 UTC, mpopetcmed commented on encapsia_cli/plugins.py
> +            "There were some errors in the plugin metadata retrieved from server"
it's because I've hacked the plugins stored procedure to return some faulty data for testing purposes (I've used the json you've sent me as source)

2023-02-06 18:26 UTC, petrem approved these changes

2023-02-06 18:27 UTC, petrem commented
fixes #110

2023-02-06 18:27 UTC, merged